name: goreleaser

on:
 pull_request:
 push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: GCC multilib
        run: |
          sudo apt-get install gcc-multilib g++-multilib clang 
          sudo apt-get install libcrypto++6 libssl1.1 libssl-dev --reinstall
      -
        name: OSXCross for CGO Support
        run: |
          mkdir ../../osxcross
          git clone https://github.com/plentico/osxcross-target.git ../../osxcross/target
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}